version: "3.8"

services:
  nginx: 
    image: nginx:${NGINX_VERSION}
    volumes: 
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./:/public/www
    ports:
      - 8006:80
    container_name: mixer_nginx_service
    restart: unless-stopped
  
  php: 
    image: php:${PHP_VERSION}
    container_name: mixer_php_service
    restart: unless-stopped
    volumes:
      - ./:/public/www
